#!/usr/bin/env python
import os, sys, csv, subprocess, shutil

if len(sys.argv) != 4:
    print "Usage: finals-munge RESULTS IN_SVG OUT_SVG"
    exit(1)

RESULTS, IN_SVG, OUT_SVG = sys.argv[1:]

slots = list("abcdefghijklmnopqrstuvwxyz01")
vals = {}
for s in slots:
    vals[s] = "?"

inp = []
f = open( RESULTS, "r" )
for line in f.readlines():
    for v in line.strip().split(","):
        if v != "":
            inp.append(v.strip())

if os.path.exists(OUT_SVG):
    os.remove(OUT_SVG)
shutil.copy( IN_SVG, OUT_SVG )

for n in range(0, len(slots)):
    print slots[n], inp[n]

    subprocess.call( "sed -e 's#>%s</tspan></text>#>%s</tspan></text>#' -i %s" % (slots[n],
                                                                                inp[n],
                                                                                OUT_SVG),
                     shell = True )
